name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/webassembly.yml
    
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [build]
      
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_wasm
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT_RELEASE_PATH }}
          
      - name: Setup release files
        run: |
          echo "PROJECT_RELEASE_NAME=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_wasm" >> $GITHUB_ENV
          
      - name: Rename file
        run: |
          mv ${{ env.PROJECT_RELEASE_PATH }} ${{ env.PROJECT_RELEASE_NAME }} 
          
      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PROJECT_RELEASE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
